[BankList]
BankList=Atmosphere, Lead, Acustic

[Banks]
Acustic=BassJazz, Orchestra, OrganJazz, StringSlow, Tank
Atmosphere=Desert, SlowCristal, Cave, FarBells, Echo_Cowbell
Lead=LeadSur, 90String

[PresetList]
PresetList=@Invalid()

[Presets]
90String=90String.padthv1
BassJazz=BassJazz.padthv1
Cave=Cave.padthv1
Desert=Desert.padthv1
Echo_Cowbell=Echo_Cowbell.padthv1
FarBells=FarBells.padthv1
LeadSur=LeadSur.padthv1
Orchestra=Orchestra.padthv1
OrganJazz=OrganJazz.padthv1
SlowCristal=SlowCristal.padthv1
StringSlow=StringSlow.padthv1
Tank=Tank.padthv1
